# Numpy - Numerical python

- It is used to perform operations on single and multidimensional arrays
- It is written in C
- All the arrays should contain homogeneous data

In [ ]:
Maths --> matrix
program ---> arrays
depp learning --> tensors

In [ ]:
pip install numpy

In [1]:
import numpy as np

# Creating an array using array function

In [2]:
lst = [34,45,56,67,87]

# print(lst , type(lst))


arr = np.array(lst)


print(arr , type(arr))

[34 45 56 67 87] <class 'numpy.ndarray'>


In [3]:
# Few important attributes


# Size - Total no of elements in your array

print(arr.size)

# shape --> Shape of an matrix

print(arr.shape) # no , 


# ndim ---> Dimension of the array

print(arr.ndim)

5
(5,)
1


In [4]:
lst = (34,45,56,67,87)

# print(lst , type(lst))


arr = np.array(lst)


print(arr , type(arr))

[34 45 56 67 87] <class 'numpy.ndarray'>


In [5]:
lst = {'a':346 , 'b':754}

# print(lst , type(lst))


arr = np.array(lst)


print(arr , type(arr))

{'a': 346, 'b': 754} <class 'numpy.ndarray'>


In [6]:
lst = {34,45,56,67,87}

# print(lst , type(lst))


arr = np.array(lst)


print(arr , type(arr))

{34, 67, 87, 56, 45} <class 'numpy.ndarray'>


# 2D

In [7]:
lst = [[1,2,3] , [4,5,6]]

# print(lst , type(lst))


arr = np.array(lst)


print(arr , type(arr))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [9]:
# Few important attributes
# Size - Total no of elements in your array
print(arr.size)
# shape --> Shape of an matrix
print(arr.shape) 

# ndim ---> Dimension of the array

print(arr.ndim)

6
(2, 3)
2


In [10]:
lst = [[1,2,3] , [4,5,6] , [7,8,9]]

# print(lst , type(lst))


arr = np.array(lst)


print(arr , type(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


# 3D

In [11]:
lst = [[[1,2,3] , [4,5,6]] , [[31,42,53] , [64,57,64]]]

# print(lst , type(lst))


arr = np.array(lst)


print(arr , type(arr))

[[[ 1  2  3]
  [ 4  5  6]]

 [[31 42 53]
  [64 57 64]]] <class 'numpy.ndarray'>


In [12]:
# Few important attributes
# Size - Total no of elements in your array
print(arr.size)
# shape --> Shape of an matrix
print(arr.shape) # depth , row , columns

# ndim ---> Dimension of the array

print(arr.ndim)

12
(2, 2, 3)
3


In [21]:
lst = [[[1,2,3] , [4,5,6]] , [[31,42,53] , [64,57,64]] , [[31,42,53] , [64,57,64]] , 
      [[31,42,53] , [64,57,64]]]

# print(lst , type(lst))


arr = np.array(lst)


print(arr , type(arr))

[[[ 1  2  3]
  [ 4  5  6]]

 [[31 42 53]
  [64 57 64]]

 [[31 42 53]
  [64 57 64]]

 [[31 42 53]
  [64 57 64]]] <class 'numpy.ndarray'>


In [22]:
arr.shape # depth , rows , columns

(4, 2, 3)

# Arange

In [23]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
np.arange(5,10 , 2)

array([5, 7, 9])

In [26]:
np.arange(10 , 0 , -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

# Linspace 

In [28]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [29]:
np.arange(10 , 101 , 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [31]:
np.linspace(10,100, 10 , dtype = int)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

# Zero's and zero like

In [32]:
np.zeros((2,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [36]:
lst = [[[1,2,3] , [4,5,6]] , [[31,42,53] , [64,57,64]] , [[31,42,53] , [64,57,64]] , 
      [[31,42,53] , [64,57,64]]]

# print(lst , type(lst))


arr = np.array(lst)


print(arr , type(arr))

[[[ 1  2  3]
  [ 4  5  6]]

 [[31 42 53]
  [64 57 64]]

 [[31 42 53]
  [64 57 64]]

 [[31 42 53]
  [64 57 64]]] <class 'numpy.ndarray'>


In [37]:
np.zeros_like(arr)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

# Ones  , one like

In [40]:
np.ones((3,4) , dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [39]:
np.ones_like(arr)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

# identity array

- It should be a square matrix row == columns

- All the dia ele are 1 and rest all are 0

In [42]:
np.identity(5 , dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Random 

In [47]:
np.random.rand(2,3)

array([[0.55494315, 0.06568239, 0.24507535],
       [0.85897166, 0.47458567, 0.99542703]])

In [48]:
np.random.randn(2,3)

array([[ 1.00186714,  0.28617621, -0.67145026],
       [-0.5709778 , -0.73621597, -1.38119334]])

In [49]:
np.random.randint(1,10 , size = (4,5))

array([[1, 1, 2, 1, 1],
       [8, 9, 6, 5, 6],
       [3, 7, 8, 7, 9],
       [4, 1, 4, 5, 7]])

In [72]:
a = np.random.randint(1,7 , size = (6  , 4))

# Transpose

In [73]:
a

array([[4, 6, 5, 2],
       [5, 4, 1, 2],
       [3, 1, 2, 4],
       [2, 4, 4, 5],
       [3, 5, 6, 5],
       [2, 6, 2, 1]])

In [74]:
a.T

array([[4, 5, 3, 2, 3, 2],
       [6, 4, 1, 4, 5, 6],
       [5, 1, 2, 4, 6, 2],
       [2, 2, 4, 5, 5, 1]])

In [76]:
a = np.identity(5 , dtype = int)

a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [77]:
a.T

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Reshape

In [81]:
asian_countries = np.array(['India' , 'Sri lanka' , 'Mayanmar' , 'Nepal' , 'Bangladesh' , 'Pakistan' ,
                  'China' , 'Bhutan'])


asian_countries

array(['India', 'Sri lanka', 'Mayanmar', 'Nepal', 'Bangladesh',
       'Pakistan', 'China', 'Bhutan'], dtype='<U10')

In [ ]:
# unistring 

where the length of all the elements is less than 10

In [84]:
asian_countries.size

8

In [86]:
asian_countries.reshape(2,4)

array([['India', 'Sri lanka', 'Mayanmar', 'Nepal'],
       ['Bangladesh', 'Pakistan', 'China', 'Bhutan']], dtype='<U10')

In [87]:
asian_countries.reshape(2,2,2)

array([[['India', 'Sri lanka'],
        ['Mayanmar', 'Nepal']],

       [['Bangladesh', 'Pakistan'],
        ['China', 'Bhutan']]], dtype='<U10')

In [88]:
asian_countries.reshape(-1 , 2)

array([['India', 'Sri lanka'],
       ['Mayanmar', 'Nepal'],
       ['Bangladesh', 'Pakistan'],
       ['China', 'Bhutan']], dtype='<U10')

In [90]:
asian_countries.reshape(2 , -1)

array([['India', 'Sri lanka', 'Mayanmar', 'Nepal'],
       ['Bangladesh', 'Pakistan', 'China', 'Bhutan']], dtype='<U10')

In [91]:
asian_countries.reshape(2 , 2 , -1)

array([[['India', 'Sri lanka'],
        ['Mayanmar', 'Nepal']],

       [['Bangladesh', 'Pakistan'],
        ['China', 'Bhutan']]], dtype='<U10')

In [100]:
asian_countries.reshape(2,-1)

array([['India', 'Sri lanka', 'Mayanmar', 'Nepal'],
       ['Bangladesh', 'Pakistan', 'China', 'Bhutan']], dtype='<U10')

In [94]:
asian_countries.size

8

# Iterating over an array

In [101]:
a = np.arange(36).reshape(6,-1)

a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [103]:
for i in a:
    print(i , end = '\n\n\n')

[0 1 2 3 4 5]


[ 6  7  8  9 10 11]


[12 13 14 15 16 17]


[18 19 20 21 22 23]


[24 25 26 27 28 29]


[30 31 32 33 34 35]




In [104]:
for i in a:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35


In [ ]:
# Ravel , flatten

In [105]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [106]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [107]:
for i in a.ravel():
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35


# Arithmetic operations on arrays element wise

In [13]:

a = [1,2,3,4,5]
b = [6,7,8,9,10]


list(map((lambda x,y:x+y) , a , b))

[7, 9, 11, 13, 15]

In [17]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])


a+b

array([ 7,  9, 11, 13, 15])

In [110]:
a * b

array([ 6, 14, 24, 36, 50])

# Operations of numpy

In [111]:
a = np.arange(24).reshape(4,-1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [112]:
a.T

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])